"""
Resume Screening Web App
-------------------------
Upload a resume (PDF) and a job description (TXT), click "Analyze",
and view a formatted screening report generated by your backend
(src/data_ingestion, src/llm, src/config modules).

Paste this file as app.py in your project root (same level as src/, data/, .env).
"""

import streamlit as st
import json
import os
import tempfile
import traceback
from src.config.file_loader import file_loader
from src.data_ingestion.data_loader import pdf_loader
from src.llm.llm import ask_llm

# ---------------------------------------------------------------------------
# Try to import your existing backend pipeline.
# Adjust these imports / function names to match what you actually have in
# src/data_ingestion/data_loader.py, src/llm/llm.py, src/config/file_loader.py
# ---------------------------------------------------------------------------



def run_screening_pipeline(resume_path: str, jd_path: str) -> dict:
    """
    Wires your uploaded files into the existing backend.
    Edit this function so the function/argument names match your real code.
    """
    
   
    job_description=file_loader(jd_path)
    resume=pdf_loader(resume_path)
    
    response = ask_llm(job_description, resume)
   
    # raw_output may already be a dict, or a JSON string from the LLM
    if isinstance(response, dict):
        return response
    return json.loads(response)


# ---------------------------------------------------------------------------
# Page config + styling
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="Resume Screening Report",
    page_icon="📄",
    layout="wide",
)

st.markdown(
    """
    <style>
    .chip {
        display: inline-block;
        padding: 4px 12px;
        margin: 3px;
        border-radius: 14px;
        font-size: 0.85rem;
        font-weight: 500;
    }
    .chip-green { background-color: #1e3d2f; color: #6fe3a3; border: 1px solid #2e6b4a; }
    .chip-red   { background-color: #3d1e1e; color: #f08080; border: 1px solid #6b2e2e; }
    .chip-blue  { background-color: #1e2c3d; color: #7fb8f0; border: 1px solid #2e4a6b; }
    .report-card {
        background-color: rgba(125,125,125,0.07);
        border: 1px solid rgba(125,125,125,0.2);
        border-radius: 10px;
        padding: 18px 20px;
        margin-bottom: 16px;
    }
    .verdict-banner {
        padding: 16px 20px;
        border-radius: 10px;
        font-size: 1.1rem;
        font-weight: 600;
        text-align: center;
    }
    .verdict-not-recommended { background-color: #3d1e1e; color: #f08080; border: 1px solid #6b2e2e; }
    .verdict-recommended { background-color: #1e3d2f; color: #6fe3a3; border: 1px solid #2e6b4a; }
    .verdict-highly-recommended { background-color: #1e3d2f; color: #6fe3a3; border: 2px solid #3fa56a; }
    .verdict-partial { background-color: #3d3a1e; color: #f0d97f; border: 1px solid #6b612e; }
    </style>
    """,
    unsafe_allow_html=True,
)

st.title("📄 AI Resume Screening")
st.caption("Upload a candidate's resume and the job description to generate an automated screening report.")

# ---------------------------------------------------------------------------
# Upload section
# ---------------------------------------------------------------------------
col1, col2 = st.columns(2)

with col1:
    resume_file = st.file_uploader("Upload Resume (PDF)", type=["pdf"])

with col2:
    jd_file = st.file_uploader("Upload Job Description (TXT)", type=["txt"])
    jd_pasted = st.text_area("...or paste the job description here instead", height=150)

analyze_clicked = st.button("🔍 Analyze Resume", type="primary", use_container_width=True)

st.divider()

# ---------------------------------------------------------------------------
# Helper renderers
# ---------------------------------------------------------------------------
def render_chips(items, style):
    if not items:
        st.write("None")
        return
    html = "".join(f'<span class="chip chip-{style}">{item}</span>' for item in items)
    st.markdown(html, unsafe_allow_html=True)


def verdict_class(status: str) -> str:
    status = (status or "").lower()
    if "highly" in status:
        return "verdict-highly-recommended"
    if "not" in status:
        return "verdict-not-recommended"
    if "partial" in status:
        return "verdict-partial"
    return "verdict-recommended"


def render_report(data: dict):
    info = data.get("candidate_information", {})
    overall = data.get("overall_assessment", {})
    breakdown = data.get("score_breakdown", {})
    skills = data.get("skills_analysis", {})
    strengths = data.get("strengths", [])
    improvements = data.get("areas_for_improvement", [])
    resume_analysis = data.get("resume_analysis", {})
    keywords = data.get("keyword_analysis", {})
    verdict = data.get("final_verdict", {})

    # --- Candidate header ---
    st.markdown('<div class="report-card">', unsafe_allow_html=True)
    h1, h2, h3 = st.columns([2, 1, 1])
    with h1:
        st.subheader(info.get("name", "Unknown Candidate"))
        st.write(f"**Target Role:** {info.get('target_role', '-')}")
        st.write(f"**Experience Level:** {info.get('experience_level', '-')}")
        st.write(f"**Education:** {info.get('education', '-')}")
    with h2:
        st.metric("Match Score", f"{overall.get('match_score', 0)}/100")
        st.progress(min(max(overall.get("match_score", 0), 0), 100) / 100)
    with h3:
        st.metric("Rating", overall.get("rating", "-"))
    st.write(f"**Recommendation:** {overall.get('recommendation', '-')}")
    st.write(overall.get("summary", ""))
    st.markdown("</div>", unsafe_allow_html=True)

    # --- Score breakdown ---
    st.markdown("### 📊 Score Breakdown")
    cols = st.columns(len(breakdown)) if breakdown else []
    for col, (key, val) in zip(cols, breakdown.items()):
        with col:
            score = val.get("score", 0)
            st.markdown(f"**{key.replace('_', ' ').title()}**")
            st.progress(min(max(score, 0), 100) / 100)
            st.caption(f"{score}/100")
            st.caption(val.get("reason", ""))

    st.markdown("---")

    # --- Skills analysis ---
    st.markdown("### 🛠️ Skills Analysis")
    s1, s2, s3 = st.columns(3)
    with s1:
        st.markdown("**✅ Matched Skills**")
        render_chips(skills.get("matched_skills", []), "green")
    with s2:
        st.markdown("**❌ Missing Skills**")
        render_chips(skills.get("missing_skills", []), "red")
    with s3:
        st.markdown("**➕ Additional Skills**")
        render_chips(skills.get("additional_skills", []), "blue")

    st.markdown("---")

    # --- Strengths / Improvements ---
    st.markdown("### 💪 Strengths & Areas for Improvement")
    c1, c2 = st.columns(2)
    with c1:
        st.markdown("**Strengths**")
        for item in strengths:
            st.markdown(f"- {item}")
    with c2:
        st.markdown("**Areas for Improvement**")
        for item in improvements:
            st.markdown(f"- {item}")

    st.markdown("---")

    # --- Resume quality ---
    st.markdown("### 📋 Resume Analysis")
    r1, r2 = st.columns([1, 2])
    with r1:
        st.metric("ATS Score", f"{resume_analysis.get('ats_score', 0)}/100")
        st.progress(min(max(resume_analysis.get("ats_score", 0), 0), 100) / 100)
        st.write(f"**Resume Quality:** {resume_analysis.get('resume_quality', '-')}")
    with r2:
        st.write("**Missing Sections**")
        for item in resume_analysis.get("missing_sections", []):
            st.markdown(f"- {item}")
        st.write("**Improvement Suggestions**")
        for item in resume_analysis.get("improvement_suggestions", []):
            st.markdown(f"- {item}")

    st.markdown("---")

    # --- Keyword analysis ---
    st.markdown("### 🔑 Keyword Analysis")
    k1, k2 = st.columns(2)
    with k1:
        st.markdown("**Matched Keywords**")
        render_chips(keywords.get("matched_keywords", []), "green")
    with k2:
        st.markdown("**Missing Keywords**")
        render_chips(keywords.get("missing_keywords", []), "red")

    st.markdown("---")

    # --- Final verdict ---
    st.markdown("### 🏁 Final Verdict")
    cls = verdict_class(verdict.get("status", ""))
    st.markdown(
        f'<div class="verdict-banner {cls}">{verdict.get("status", "-")}</div>',
        unsafe_allow_html=True,
    )
    st.caption(verdict.get("reason", ""))


# ---------------------------------------------------------------------------
# Main logic
# ---------------------------------------------------------------------------
if analyze_clicked:
    if not resume_file:
        st.warning("Please upload a resume PDF.")
    elif not jd_file and not jd_pasted.strip():
        st.warning("Please upload a job description file or paste the job description text.")
    else:
        with st.spinner("Analyzing resume against job description..."):
            try:
                with tempfile.TemporaryDirectory() as tmpdir:
                    resume_path = os.path.join(tmpdir, resume_file.name)
                    with open(resume_path, "wb") as f:
                        f.write(resume_file.getbuffer())

                    if jd_file:
                        jd_path = os.path.join(tmpdir, jd_file.name)
                        with open(jd_path, "wb") as f:
                            f.write(jd_file.getbuffer())
                    else:
                        jd_path = os.path.join(tmpdir, "job_description.txt")
                        with open(jd_path, "w", encoding="utf-8") as f:
                            f.write(jd_pasted)

                    report_data = run_screening_pipeline(resume_path, jd_path)

                st.session_state["report_data"] = report_data
                st.success("Analysis complete!")
            except Exception as e:
                st.error(f"Something went wrong while generating the report: {e}")
                with st.expander("Show error details"):
                    st.code(traceback.format_exc())

# ---------------------------------------------------------------------------
# Render last generated report (persists across reruns)
# ---------------------------------------------------------------------------
if "report_data" in st.session_state:
    render_report(st.session_state["report_data"])

    with st.expander("View Raw JSON"):
        st.json(st.session_state["report_data"])